/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FamilyMember = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat32;
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([FamilyMember], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMember' : IDL.Func([], [IDL.Bool], ['query']),
  'listMembers' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
  'postMessage' : IDL.Func([IDL.Text], [MessageId], []),
  'removeMember' : IDL.Func([FamilyMember], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FamilyMember = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat32;
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([FamilyMember], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMember' : IDL.Func([], [IDL.Bool], ['query']),
    'listMembers' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
    'postMessage' : IDL.Func([IDL.Text], [MessageId], []),
    'removeMember' : IDL.Func([FamilyMember], [], []),
  });
};

export const init = ({ IDL }) => { return []; };